CREATE DATABASE DEPARTMENT;
GO
USE DEPARTMENT;
GO
CREATE TABLE EMPLOYEES
(
EMPLOYEE_ID INT IDENTITY(1,1) PRIMARY KEY,
EMPLOYEE_NAME VARCHAR(100) NOT NULL,
HIRE_DATE DATE DEFAULT '22-09-2024',
EMAIL VARCHAR(100) UNIQUE,
SALARY DECIMAL(10,2) CHECK (SALARY>5000),
DEPARTMENT_ID INT
);
GO
SELECT * FROM EMPLOYEES;



