TOPICS_TO_BE_COVERED;
1) INTRODUCTION TO DATABASE
2) TYPES OF SQL COMMANDS
DDL, DML, DRL/DQL, TQL, TCL, DCL
3) CONSTRAINTS
4) OPERATORS & CLAUSES

CREATE DATABASE evening_batch;
USE evening_batch
drop database evening_batch
create database akshit
PANCARD char(10);

create table teachers
(
TEACHERID INT,
DEPARTMENTID INT,
NAME VARCHAR(100),
JOB VARCHAR(50),
SALARY DECIMAL(10,2),
)
INSERT INTO TEACHERS (TEACHERID, DEPARTMENTID, NAME, JOB, SLARY)
VALUE (1,123,'SHAVETA SOOD','MATHS TEACHER',45000.31),
SELECT*FROM teachers

